# Generated by Django 5.0.7 on 2024-08-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовoк задачи')),
                ('description', models.TextField(verbose_name='Описание для задачи')),
                ('completed', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
